In [1]:
import numpy as np
from numpy import linalg as la

In [2]:
A=[[1,-1],[3,2],[1,1],[1,0]]
A=np.array(A,dtype=float)
A

array([[ 1., -1.],
       [ 3.,  2.],
       [ 1.,  1.],
       [ 1.,  0.]])

In [3]:
R=np.copy(A)
for j in range(1,len(R)):
    G=np.eye(len(R))
    ro=la.norm([R[0,0],R[j,0]])
    c=R[0,0]/ro
    s=R[j,0]/ro
    G[0,0]=c; G[0,j]=s;
    G[j,j]=c; G[j,0]=-s;
    R=G@R
    R=np.round(R,5)
    print(R)
    print("\n")

[[3.16228 1.58114]
 [0.      1.58114]
 [1.      1.     ]
 [1.      0.     ]]


[[3.31663 1.80907]
 [0.      1.58114]
 [0.      0.47673]
 [1.      0.     ]]


[[ 3.46411  1.73205]
 [ 0.       1.58114]
 [ 0.       0.47673]
 [-0.      -0.52223]]




In [7]:
R2=np.copy(R)
for j in range(2,len(R2)):
    G=np.eye(len(R2))
    ro=la.norm([R2[1,1],R2[j,1]])
    print(R2[1,1],R2[j,1])
    print("\n")
    c=R2[1,1]/ro
    s=R2[j,1]/ro
    G[1,1]=c; G[1,j]=s;
    G[j,j]=c; G[j,1]=-s;
    R2=G@R2
    R2=np.round(R2,5)
    print(R2)
    print("\n")

1.58114 0.47673


[[ 3.46411  1.73205]
 [ 0.       1.65145]
 [ 0.       0.     ]
 [ 0.      -0.52223]]


1.65145 -0.52223


[[ 3.46411  1.73205]
 [ 0.       1.73205]
 [ 0.       0.     ]
 [ 0.      -0.     ]]


