In [ ]:
import numpy as np
from numpy import linalg as la

In [ ]:
A=[[-1,-1,1],[1,3,3],[-1,-1,5]]
A=np.array(A)
A

array([[-1, -1,  1],
       [ 1,  3,  3],
       [-1, -1,  5]])

In [ ]:
alpha=np.sign(A[0,0])*la.norm(A[:,0])
ei=np.zeros(len(A))
ei[0]=1

v=A[:,0]-alpha*ei
v=v.reshape(-1,1)
v_vt=v@v.T
vt_v=v.T@v
vt_v=vt_v[0,0]
Id=np.eye(len(A))
H=np.zeros_like(A)

H=Id-(2/vt_v)*v_vt
a=H@A[:,0]
a=np.round(a,5)
R=np.copy(A)
R[:,0]=a
R

array([[-1, -1,  1],
       [ 0,  3,  3],
       [ 0, -1,  5]])

In [ ]:
R[1:,1:]

array([[ 3,  3],
       [-1,  5]])

In [ ]:
A_n=R[1:,1:]
alpha=np.sign(A_n[0,0])*la.norm(A_n[:,0])
ei=np.zeros(len(A_n))
ei[0]=1

v=A_n[:,0]-alpha*ei
v=v.reshape(-1,1)
v_vt=v@v.T
vt_v=v.T@v
vt_v=vt_v[0,0]
Id=np.eye(len(A_n))
H=np.zeros_like(A_n)

H=Id-(2/vt_v)*v_vt
a=H@A_n[:,0]
a=np.round(a,5)
R_n=np.copy(A_n)
R_n[:,0]=a
R_n

array([[3, 3],
       [0, 5]])

In [ ]:
R[1:,1:]=R_n
R

array([[-1, -1,  1],
       [ 0,  3,  3],
       [ 0,  0,  5]])

In [ ]:
a={}
for i in range(1,5):
  na="a_"+str(i)
  a[na]=i*[0.0]

In [ ]:
a

{'a_1': [0.0],
 'a_2': [0.0, 0.0],
 'a_3': [0.0, 0.0, 0.0],
 'a_4': [0.0, 0.0, 0.0, 0.0]}