In [3]:
import numpy as np
def lu_pivot_total(A):
    n = A.shape[0]
    P = np.eye(n)  # Matriz de permutación inicial
    LU = A.copy()
    
    for k in range(n - 1):
        pivot_row = np.argmax(np.abs(LU[k:n, k])) + k
        print(pivot_row)
        if pivot_row != k:
            P[[k, pivot_row]] = P[[pivot_row, k]]
            LU[[k, pivot_row]] = LU[[pivot_row, k]]
        
        for i in range(k + 1, n):
            LU[i, k] /= LU[k, k]
            for j in range(k + 1, n):
                LU[i, j] -= LU[i, k] * LU[k, j]

    return P, LU

# Ejemplo de uso
A = np.array([[2, 1, 1],
              [4, 3, 3],
              [8, 7, 9]], dtype=float)

P, LU = lu_pivot_total(A)
"""print("Matriz de permutación P:")
print(P)
print("Matriz triangular inferior L y superior U:")
print(LU)"""


2
2


'print("Matriz de permutación P:")\nprint(P)\nprint("Matriz triangular inferior L y superior U:")\nprint(LU)'

In [5]:
P = np.eye(3)
P

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [7]:
P[[2, 1]]=P[[1, 2]]
P

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 1., 0.]])

In [8]:
P[[2, 1]]

array([[0., 1., 0.],
       [0., 0., 1.]])

In [11]:
P[0:3,0]

array([1., 0., 0.])