In [1]:
import numpy as np
def lu_pivot_total(A):
    n = A.shape[0]
    P = np.eye(n)  # Matriz de permutación inicial
    LU = A.copy()
    
    for k in range(n - 1):
        pivot_row = np.argmax(np.abs(LU[k:n, k])) + k
        print(pivot_row)
        print(f"K{k}")
        print(f"P{P}")
        print(f"LU{LU}")
        if pivot_row != k:
            P[[k, pivot_row]] = P[[pivot_row, k]]
            LU[[k, pivot_row]] = LU[[pivot_row, k]]
            print(f"pivot_row , k{pivot_row , k}")
            print(f"P{P}")
            print(f"LU{LU}")
        for i in range(k + 1, n):
            LU[i, k] /= LU[k, k]
            for j in range(k + 1, n):
                LU[i, j] -= LU[i, k] * LU[k, j]
        print("Despues de LU")
        print(f"P{P}")
        print(f"LU{LU}")
    return P, LU

# Ejemplo de uso
A = np.array([[2, 1, 1],
              [4, 3, 3],
              [8, 7, 9]], dtype=float)

P, LU = lu_pivot_total(A)


2
K0
P[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
LU[[2. 1. 1.]
 [4. 3. 3.]
 [8. 7. 9.]]
pivot_row , k(2, 0)
P[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
LU[[8. 7. 9.]
 [4. 3. 3.]
 [2. 1. 1.]]
Despues de LU
P[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
LU[[ 8.    7.    9.  ]
 [ 0.5  -0.5  -1.5 ]
 [ 0.25 -0.75 -1.25]]
2
K1
P[[0. 0. 1.]
 [0. 1. 0.]
 [1. 0. 0.]]
LU[[ 8.    7.    9.  ]
 [ 0.5  -0.5  -1.5 ]
 [ 0.25 -0.75 -1.25]]
pivot_row , k(2, 1)
P[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
LU[[ 8.    7.    9.  ]
 [ 0.25 -0.75 -1.25]
 [ 0.5  -0.5  -1.5 ]]
Despues de LU
P[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
LU[[ 8.          7.          9.        ]
 [ 0.25       -0.75       -1.25      ]
 [ 0.5         0.66666667 -0.66666667]]


In [3]:
print("Matriz de permutación P:")
print(P)
print("Matriz triangular inferior L y superior U:")
print(LU)


Matriz de permutación P:
[[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Matriz triangular inferior L y superior U:
[[ 8.          7.          9.        ]
 [ 0.25       -0.75       -1.25      ]
 [ 0.5         0.66666667 -0.66666667]]
