In [1]:
import numpy as np

# Ejemplo de uso
A = np.array([[2, 1, 1],
              [4, 3, 3],
              [8, 7, 9]], dtype=float)

In [2]:
def lu_pivot_total(A):
    n = A.shape[0]
    P = np.eye(n)  # Matriz de permutación inicial
    U = A.copy()
    L=np.identity(n)
    
    for k in range(n - 1):
        pivot_row = np.argmax(np.abs(U[k:n, k])) + k
        if pivot_row != k:
            P[[k, pivot_row]] = P[[pivot_row, k]]
            U[[k, pivot_row]] = U[[pivot_row, k]]
            L[[k, pivot_row]] = L[[pivot_row, k]]
        for i in range(k + 1, n):
            factor=U[i, k] / U[k, k]
            L[i, k]=factor
            for j in range(k + 1, n):
                U[i, j] = U[i, j]- factor * U[k, j]

    return P, U,L

In [3]:
P, U, L = lu_pivot_total(A)
P,U, L

(array([[0., 0., 1.],
        [1., 0., 0.],
        [0., 1., 0.]]),
 array([[ 8.        ,  7.        ,  9.        ],
        [ 2.        , -0.75      , -1.25      ],
        [ 4.        , -0.5       , -0.66666667]]),
 array([[0.        , 0.        , 1.        ],
        [0.25      , 0.        , 0.        ],
        [0.5       , 0.66666667, 0.        ]]))