In [1]:
import numpy as np

In [2]:
def factorizacionLU(A):
    # dimension de la matriz
    n = len(A)
    # matriz L inicialmente es la identidad
    L = np.identity(n)
    # inicialmente la matriz A y la matriz U son iguales
    U = np.zeros((n,n))
    for i in range(0,n):
        for j in range(0,n):
            U[i][j] = A[i][j]
    # eliminacion gaussiana
    for i in range(0,n):
        for j in range(i+1,n):
            # guardar los factores de eliminacion gaussiana 
            # en la matriz L
            factor = U[j][i]/U[i][i]
            L[j][i] = factor
            # realizar eliminacion gaussiana en la matriz U
            # para quedar de forma triangular superior
            for k in range(i,n):
                U[j][k] = U[j][k] - factor*U[i][k]
    return L,U

In [3]:
# algoritmo para sustitucion hacia delante
# n es el tamano de la dimension del problema
# matriz L, vector b ya estan dados como parametros
# guardar los resultados en el vector y
# Ly=b
def sustDelante(L, b):
    n=len(L)
    y=np.empty_like(b)
    y[0] = b[0]
    for i in range(1,n):
        y[i] = b[i]
        for j in range(0,i):
            y[i] -= L[i][j]*y[j]
    return y

# algoritmo para sustitucion hacia atras
# n es el tamano de la dimension del problema
# matriz U, vector y ya estan dados como parametros
# guardar los resultados en el vector x
# Ux=y
def sustAtras(U, y):
    n=len(U)
    x=np.empty_like(y)
    x[n-1] = y[n-1]/U[n-1][n-1]
    for i in range(n-2,-1,-1):
        x[i] = y[i]
        for j in range(i+1,n):
            x[i] -= U[i][j]*x[j]
        x[i] /= U[i][i]
    return x

In [4]:
# matriz del sistema Ax=b
A = np.array([[-4.0,-3.0,1.0],[8.0,11.0,-1.0],[4.0,18.0,5.0]])
# vector b = A*xTeor, producto matriz A con vector xTeor 
b = np.array([5.0,6.0,1.0])
# llamar funcion de descomposicion LU para obtener/llenar matrices L,U

def LU_solver(A,b):
    L,U=factorizacionLU(A)
    #se imprimen las matrices y el vector b
    print(A)
    print(L)
    print(U)
    print(b)
    # llamar funcion sustDelante para obtener/llenar vector y
    y = sustDelante(L,b)    
    # llamar funcion sustAtras para obtener/llenar vector x 
    # solucion aproximada/calculada
    x = sustAtras(U,y)
    # imprimir solucion aproximada/calculada
    print(x)
    
LU_solver(A,b)

[[-4. -3.  1.]
 [ 8. 11. -1.]
 [ 4. 18.  5.]]
[[ 1.  0.  0.]
 [-2.  1.  0.]
 [-1.  3.  1.]]
[[-4. -3.  1.]
 [ 0.  5.  1.]
 [ 0.  0.  3.]]
[5. 6. 1.]
[ -9.25   6.   -14.  ]


In [5]:
# comprobacion con numpy
x = np.linalg.solve(A,b)
print(x)

[ -9.25   6.   -14.  ]


In [6]:
def Cholesky(A):
    n=A.shape[0]
    L=np.zeros_like(A)

    for k in range(n):
        for i in range(k+1):
            if k==i:
                sum=0.0
                for j in range(k):
                    sum+= L[k][j]*L[k][j]
                L[k][k]=np.sqrt(A[k][k]-sum)

            else:
                sum=0.0
                for j in range(i):
                    sum+= L[i][j]*L[k][j]
                L[k][i]=(A[k][i]-sum)/L[i][i]
    return L

In [7]:
# se define la matriz A
AA = np.array([[6.0,15.0,55.0],[15.0,55.0,225.0],[55.0,225.0,979.0]])

# se define la matriz A
bb = np.array([76.0, 295.0, 1259.0])

def Cholesky_Solver(AA,bb):
    # funcion de numpy encargada de la factorizacion Cholesky
    L = Cholesky(AA)

    # Dado que se usara Lt varias veces, es mejor guardarla en memoria
    Lt = L.T

    # mostrar ambas matrices
    print(L)
    print(Lt)

    # se comprueba el resultado
    print(np.matmul(L,Lt))

    # nuevo vector b'
    y = np.linalg.solve(L,bb)

    print(y)

    # usando sustitucion hacia atras
    x =  np.linalg.solve(Lt,y)

    # mostrar solucion usando sustAtras
    print(x)
    
Cholesky_Solver(AA,bb)

[[ 2.44948974  0.          0.        ]
 [ 6.12372436  4.18330013  0.        ]
 [22.45365598 20.91650066  6.11010093]]
[[ 2.44948974  6.12372436 22.45365598]
 [ 0.          4.18330013 20.91650066]
 [ 0.          0.          6.11010093]]
[[  6.  15.  55.]
 [ 15.  55. 225.]
 [ 55. 225. 979.]]
[31.02687008 25.0998008   6.11010093]
[1. 1. 1.]


In [8]:
# comprobacion con numpy
x = np.linalg.solve(AA,bb)
print(x)

[1. 1. 1.]
